### PR TITLE
Update Package Version

### PR DESCRIPTION
**Pull request by ShalokShalom**
http://funkyimg.com/view/Ziee

### CODE REVIEW

**Comment by demmm** [comment]
Look at the PKGBUILD, it automatically updates the git version for every build.

**Comment by ShalokShalom** [comment]
Look at my Screenshot, the name, which appears in Octopi is different and with that, confusing ?

**Comment by demmm** [comment]
As said on IRC, open an issue on octopi.

**Comment by ShalokShalom** [comment]
Even when this is fixed in Octopi, is the pkgver still wrong ??

Current is 121, while the PKGBUILD contains the number 56.

Two Bugs: Octopi and PKHBUILD 

Octopi change old and new, PKGBUILD contain the old.

From where get Octopi the correct Number, by the way ?

**Pull request closed without merging**
